# pull the Node Docker image
FROM node

# Create the directory inside the container for the app
WORKDIR /usr/src/app

# our app is running on port 5000 within the container, so need to expose it
EXPOSE 5000

# the command that starts our app
CMD ["npm", "run", "start_server"]